import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class HelpSupportScreen extends StatelessWidget {
  const HelpSupportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Help & Support', style: TextStyle(color: AppColors.textPrimary)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // FAQ Section
            _buildSectionTitle('Frequently Asked Questions'),
            const SizedBox(height: 12),
            _FaqTile(
              question: 'How does the AI tutor work?',
              answer: 'The AI tutor uses RAG (Retrieval-Augmented Generation) technology to provide accurate answers based on the HKDSE ICT curriculum. It searches through course materials and generates personalised responses.',
            ),
            _FaqTile(
              question: 'Can I use the app offline?',
              answer: 'Notes and quiz results are cached locally for offline review. However, the AI chat and generating new content requires an internet connection.',
            ),
            _FaqTile(
              question: 'How are quizzes generated?',
              answer: 'Quizzes are dynamically generated by AI based on the topic content. Each attempt may have different questions to ensure comprehensive learning.',
            ),
            _FaqTile(
              question: 'What does the difficulty level do?',
              answer: 'The difficulty level adjusts the complexity of AI-generated content and quiz questions. Beginner provides simpler explanations, while Advanced includes more technical detail.',
            ),
            _FaqTile(
              question: 'How is my progress tracked?',
              answer: 'Progress is tracked by completed topics and quiz scores. The overall progress reflects how many topics you\'ve completed across all modules.',
            ),
            const SizedBox(height: 24),

            // Contact
            _buildSectionTitle('Contact Us'),
            const SizedBox(height: 12),
            _buildContactCard([
              _ContactTile(
                icon: Icons.email_outlined,
                iconColor: AppColors.primary,
                title: 'Email Support',
                subtitle: 'support@ictlearn.app',
              ),
              _ContactTile(
                icon: Icons.bug_report_outlined,
                iconColor: AppColors.warning,
                title: 'Report a Bug',
                subtitle: 'Help us improve the app',
              ),
              _ContactTile(
                icon: Icons.feedback_outlined,
                iconColor: AppColors.accent,
                title: 'Send Feedback',
                subtitle: 'We\'d love to hear from you',
              ),
            ]),
            const SizedBox(height: 24),

            // About
            _buildSectionTitle('About'),
            const SizedBox(height: 12),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: AppColors.card,
                borderRadius: BorderRadius.circular(14),
                border: Border.all(color: AppColors.cardBorder),
              ),
              child: Column(
                children: [
                  Container(
                    width: 56,
                    height: 56,
                    decoration: BoxDecoration(
                      gradient: AppGradients.primary,
                      borderRadius: BorderRadius.circular(14),
                    ),
                    child: const Icon(Icons.menu_book_rounded, color: Colors.white, size: 28),
                  ),
                  const SizedBox(height: 12),
                  Text('ICTorch', style: TextStyle(color: AppColors.textPrimary, fontSize: 18, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 4),
                  Text('Version 1.0.0', style: TextStyle(color: AppColors.textSecondary, fontSize: 13)),
                  const SizedBox(height: 8),
                  Text(
                    'An AI-powered ICT learning platform\nfor HKDSE students',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: AppColors.textMuted, fontSize: 13),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String text) {
    return Text(
      text,
      style: TextStyle(color: AppColors.textPrimary, fontSize: 16, fontWeight: FontWeight.w600),
    );
  }

  Widget _buildContactCard(List<_ContactTile> tiles) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.card,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.cardBorder),
      ),
      child: Column(
        children: tiles.asMap().entries.map((entry) {
          final tile = entry.value;
          final isLast = entry.key == tiles.length - 1;
          return Column(
            children: [
              ListTile(
                leading: Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: tile.iconColor.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(tile.icon, color: tile.iconColor, size: 20),
                ),
                title: Text(tile.title, style: TextStyle(color: AppColors.textPrimary, fontSize: 15)),
                subtitle: Text(tile.subtitle, style: TextStyle(color: AppColors.textSecondary, fontSize: 12)),
                trailing: Icon(Icons.chevron_right, color: AppColors.textMuted, size: 20),
              ),
              if (!isLast)
                Divider(height: 1, indent: 60, color: AppColors.cardBorder),
            ],
          );
        }).toList(),
      ),
    );
  }
}

class _FaqTile extends StatefulWidget {
  final String question;
  final String answer;

  const _FaqTile({required this.question, required this.answer});

  @override
  State<_FaqTile> createState() => _FaqTileState();
}

class _FaqTileState extends State<_FaqTile> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        color: AppColors.card,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.cardBorder),
      ),
      child: Column(
        children: [
          ListTile(
            title: Text(
              widget.question,
              style: TextStyle(color: AppColors.textPrimary, fontSize: 14, fontWeight: FontWeight.w500),
            ),
            trailing: AnimatedRotation(
              turns: _expanded ? 0.5 : 0,
              duration: const Duration(milliseconds: 200),
              child: Icon(Icons.expand_more, color: AppColors.textMuted),
            ),
            onTap: () => setState(() => _expanded = !_expanded),
          ),
          AnimatedCrossFade(
            firstChild: const SizedBox.shrink(),
            secondChild: Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              child: Text(
                widget.answer,
                style: TextStyle(color: AppColors.textSecondary, fontSize: 13, height: 1.5),
              ),
            ),
            crossFadeState: _expanded ? CrossFadeState.showSecond : CrossFadeState.showFirst,
            duration: const Duration(milliseconds: 200),
          ),
        ],
      ),
    );
  }
}

class _ContactTile {
  final IconData icon;
  final Color iconColor;
  final String title;
  final String subtitle;

  const _ContactTile({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.subtitle,
  });
}
